### ISSUE TITLE
normalize root.p

### ISSUE THREAD

**Issue by bomeara** [thej022214/corHMM#1]
root.p, if given by user, doesn't normalize (root.p/sum(root.p)). This is bad.

**Comment by thej022214** [comment]
Appreciate the hyperbole. But if I understand you correctly, this is a fail safe for users that provide a vector that doesn't sum to 1?

**Comment by bomeara** [comment]
Wow, that was fast. Yep, failsafe for such users.

**Comment by bomeara** [comment]
the argument was that *other* R packages normalize. So they assume same behavior here

**Comment by thej022214** [comment]
Ok. Will make this change. Though, I shall debate internally whether or not to code a snarky message to pop up when triggered...

(kidding)

**Comment by bomeara** [comment]
I could also do it -- but teaching now. But I'm all for snarky messages. ```warning("arithmetic is hard for you. Think about your life choices")```
