### ISSUE TITLE
rayDISC:  Warning message: In prepareDataFitch(data) : NAs introduced by coercion to integer range

### ISSUE THREAD

**Issue by Tambura10** [thej022214/corHMM#10]
Dear Jeremy,

first of all, thank you very much for Package ‘corHMM’ :).
I've tried to perform rayDISC with  to a trait with 41 states applied to polymorphic taxa (as you reported below). Unfortunately, I have obtained this:

--------------------------------------------------------------------
State distribution in data:
States:             1          1&3&4            1&4     10        10&2   10&26 10&4   10&4&13        10&6   11             11&1   11&15 11&4   12        12&1   13&10 14&10 15        15&11 15&19 15&19&32      15&22             15&22&2        15&22&29      15&23 15&27 15&29 15&32 15&4   15&4&32        15&6   15&8             16        17        18        18&15 18&15&10      18&19 18&4   18&8&4          19        19&10 19&18             19&32 19&33 19&4   19&6   2           2&4     20        21        24&1&4          25        27        3             3&10   3&2     3&4     31        32        34        4          4&1     4&10   4&13   4&30   5          5&1&4             5&10&4          5&11&4          5&18&19        5&34   5&4     6          6&10   6&4     7&27   7&28             8          8&2     9          9&18&19        9&19   9&4     
Counts:           3          1          7          13        1          3          23        1          1          1          1          1             1          2          1          1          3           25        1          3          6          2          2          1          1             1          2          1          4          1           1          1          2          2          6          3          1          1             8          1          12        1          1           1          1          3          1          8          1          1          2             1          2          1          4          2           2          6          1          1          1          23        2          4             2          1          2          1          3           1          1          1          5          4          2          1          1             1          1          1          2          1           1          3          
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using joint reconstruction. 
Kicking in arbitrary precision package Rmpfr due to very low probabilities.
Kicking in arbitrary precision package Rmpfr due to very low probabilities.
Warning message:
In prepareDataFitch(data) : NAs introduced by coercion to integer range
----------------------------------------------------------------------

What is wrong? Could you suggest me a solution, please?
Thanks a lot for your attention and support

All my best
Franco

**Comment by jcoliver** [comment]
Thank you for this, @Tambura10 . The warning is being thrown by a function in the phangorn package, but we'll take a look.

**Comment by thej022214** [comment]
This is not a major warning and should run ok. But have dealt with it inside of corHMM.
