### ISSUE TITLE
Primates file format

### ISSUE THREAD

**Issue by GhadeerB** [thej022214/corHMM#17]
Hi,

This is Ghadeer, I am trying to use the corHMM and I have question please. 

While using corHMM on my data, it resulted in warinings with this message "NAs introduced by coercion". Also, I noticed that the state distribution-state was indicated as a “?” (attached). May I ask what the possible reason for is? Please let me know if you need our tree and state files. Thank you.

Best,
Ghadeer
<img width="520" alt="GitHub" src="https://user-images.githubusercontent.com/45635697/90801421-de1b3500-e2e3-11ea-9a03-1ad472d18004.png">

**Comment by jboyko** [comment]
It will be easier to debug if you can send a sample of your phylogeny and dataset to us. Email it to jboyko@uark.edu and I'll take a closer look.

**Comment by GhadeerB** [comment]
Sure, that would be great. I will email you soon, thank you.

**Comment by jboyko** [comment]
This error has been resolved. The species names were lower case in the dataset and upper case in the phylogeny.
