### ISSUE TITLE
makeSimmap returns vector size error 

### ISSUE THREAD

**Issue by vficarrotta** [thej022214/corHMM#20]
I am given the error that a vector of size 3096 Gb cannot be allocated.  This error did not exist when the function makeSimmap() was in the following form: 
**simmap <- makeSimmap(tree=phy, tip.states=tip.states, states=states, model=model, nSim=10, nCores=1)**
After the update to the function that changed the argument format, I began receiving the vector size error.  It happens no matter the number of simulations and on multiple machines using R version 4.0.3.  Not tested in R Studio.

**Comment by jboyko** [comment]
Are you able to run the example?

```
data(primates)
phy <- primates[[1]]
phy <- multi2di(phy)
data <- primates[[2]]

##run corhmm
MK <- corHMM(phy, data, 1)

##get simmap from corhmm solution
model <- MK$solution
simmap <- makeSimmap(tree=phy, data=data, model=model, rate.cat=1, nSim=1, nCores=1)
```

**Comment by vficarrotta** [comment]
I realized I wasn't running the latest github version of corHMM after I
failed to run the code in your email.  After pulling the package from
github, I successfully ran your code and mine.  Thank you for the quick
reply - this had me running in circles for 2hrs last night.  I will delete
my issue submission.

Vince

**Comment by jboyko** [comment]
Ha, no problem. Glad it's solved.
