### ISSUE TITLE
Errors when NA's are present in character data

### ISSUE THREAD

**Issue by HeatherKates** [thej022214/corHMM#21]
I have been unable to get corHMM to run on a dataset with missing data (example with simulated data attached as .txt for github but should be .R). 

I have messed around to try to get NA values to work, trying "" "NA" NA and "1&2". CorHMM() will run with NAs if get.tip.states=FALSE, but downstream steps fail.

(I looked through the source code and see that under the #JDB Modified Functions function rate.cat.set.corHMM.JDB, these lines were commented out (lines 434-437):
```
#this is being removed temporarily - this handles NA tip states
# for (i in 1:nb.tip){if(is.na(x[i]00{x[i]=2}}
```
I don't know if that's relevant because none of the code under #The various utility functions used and #JDB Modified Functions code appears in the corHMM function on cran (or from source, or from github, all tried), but seeing it did make me wonder if maybe code to handle NAs was in an older version but not carried through to an update. I tried installing some old versions, but then get explicit errors like "Found unknown characters (not supplied in levels). Deleted sites with with unknown states." 

Thanks for any help with this,
Heather Rose
[corHMM.NAissue.txt](https://github.com/thej022214/corHMM/files/5768168/corHMM.NAissue.txt)

**Comment by jboyko** [comment]
Hi Heather,

corHMM handles missing data with "?" instead of NA. We learned a little while ago the help file was out of date and updated it, but I'm not sure that version made it to CRAN before they shut down updates for the holidays. Here is the most recent description:

> Ambiguities (polymorphic taxa or taxa missing data) are assigned likelihoods following Felsenstein (2004, p. 255). Taxa with missing data are coded “?” with all states observed at a tip. Polymorphic taxa are coded with states separated by an “&”. For example, if a trait has four states and taxonA is observed to be in state 1 and 3, the character would be coded as “1&3”. corHMM then uses this information to assign a likelihood of 1.0 to both states. Missing data are treated as ambiguous for all states, thus all states for taxa missing data are assigned a likelihood of 1.0. For example, for a four-state character (i.e. DNA), a taxon missing data will have likelihoods of all four states equal to 1.0 [e.g. L(A)=1.0, L(C)=1.0, L(G)=1.0, L(T)=1.0].

Based on the code you provided, changing `charstatesNA <- c(rep(0,8),rep(1,8),rep("",4))` to `charstatesNA <- c(rep(0,8),rep(1,8),rep("?",4))` would resolve the issue. 

Best,
James

**Comment by HeatherKates** [comment]
Hi James,

YES, that worked- thank you! And thanks for the very fast response!

Heather Rose

**Comment by jboyko** [comment]
No problem, glad it's resolved!

Best,
James
