### ISSUE TITLE
root state probabilities with hidden rates

### ISSUE THREAD

**Issue by HeatherKates** [thej022214/corHMM#22]
Hello, 
I need to know what the order of elements should be in the root vector, including for different numbers of rate categories.

From the corHMM manual:

> The user can fix the root state probabilities by supplying a vector to root.p. For example, if the
> hypothesis is that the root is 0_S in a model with two hidden rates, then the root vector would
> be root.p=c(1,0,0,0) for state combinations 0_S, 1_S, 0_F, and 1_F, respectively.

I'm unsure here whether "S" and "F" refer to rates (slow and fast?) or whether they're specific to the user's data in this example. I haven't seen S and F used to denote rates anywhere else in the documentation. 

For example, if I specify two rate categories and my data has one trait that has two states "absent" and "present" with the default state matrix assigned as:     
 ```
1         2 
 "Absent" "Present"  
```
and I want to fix the root probabilities to be "absent" and rate 2, would my vector be:
`root.p=c(0,0,1,0)`? 
And how does this extend to a 3 rate model? And what if I want to constrain the state but not the rate, in the above example is it then `root.p=c(1,0,1,0)`?

Thank you!

**Comment by jboyko** [comment]
Ya, that's exactly right. 

For a 3 state model if you wanted the root probabilities fixed for 2B root.p=c(0,0,1,0,0,0) and if you wanted to constrain it to be any rate category, but state 2 it would be root.p=c(0,1,0,1,0,1).

**Comment by HeatherKates** [comment]
Great, thanks for the explanation!
