### ISSUE TITLE
Default rate matrices are not "ARD"

### ISSUE THREAD

**Issue by HeatherKates** [thej022214/corHMM#24]
[ARDIssue.R.txt](https://github.com/thej022214/corHMM/files/6702939/ARDIssue.R.txt)
Hello,

 The manual explains that the default model/rate matrix should be "ARD", all rates differ. In the matrices (and solutions) produced using the defaults (or specifying model="ARD"), all rates do not differ. For example, rates from hidden rate category 1 to hidden rate category 2 are equal in every observed state. (So if there are three observed states and two hidden rate categories like in the attached example, ten different rates are estimated instead of 14 because A,R2->A,R1 = B,R2->B,R1 = C,R2->C,R1 and A,R1->A,R2 = B,R1->B,R2 = B,R1->R2

Have I misunderstood something about ARD or is this an error? When I want an ARD model I've been manually adjusting the rate matrices so that all rates are different and want to make sure this is what I should be doing.
Thank you,
Heather Rose

**Comment by jboyko** [comment]
Hi Heather,

You are correct, all transitions between rate classes (R1, R2, etc.) occur at the same rate regardless of the observed (A, B, etc.) state. However, this is by design. We believe that estimating these transitions is likely difficult and possibly unidentifiable. There is even debate whether we should allow R1 to R2 to differ from R2 to R1. If you would like to allow these transitions to occur you will have to make the index matrix yourself and provide a rate.mat argument. But, I'd warn that this is a highly contentious model structure and probably would additional work to ensure it is estimable.

Best,
James

**Comment by HeatherKates** [comment]
Thanks James,
I think I understand from a modeling perspective what you mean, but I'm struggling to explain the resulting equal transition rates in a biological context. 

From Boyko and Beaulieu 2020:
"Each of these models allows for the possibility of rate heterogeneity through the inclusion of a hidden state; however, the state-dependent processes differ....The ARD/ARD model specifies that there could be a bias towards a particular state, but this state may differ depending on whether the lineage is in R1 or R2." 

I understood that "bias toward a particular state" means the transition rate from state 1 to state 2 can differ from the transition rate from state 2 to state 1, and that "this state may differ depending on whether the lineage is..." means the rates between state 1 to state 2 can differ between R1 and R2. I can't find the explanation you provided here in a paper or with a biological interpretation. Do you know where I could find a more in-depth explanation and interpretation of this (I expect the fact that I don't have a strong modeling background is the issue here, but neither will most who view our resulting transition rate matrix and reconstruction)?

Thanks for your time!

**Comment by jboyko** [comment]
Hi Heather,

Ya, that's a great question and I totally understand. The biological interpretation of parameters is something that I often struggle with too. I can't think of anything of the top of my head to help. Perhaps the original corHMM paper: https://onlinelibrary.wiley.com/doi/full/10.1111/evo.12180?. Check out the section that starts "Before moving forward, a remark about the biological meaning of the HRM is warranted". Let me know if that helps, if not ping me again and I can try and give further explanation.

**Comment by HeatherKates** [comment]
Thanks! I have read that section (a few times ( : ) and I still struggle, but for now I will leave this and do you as you advised. For now! You can close this.
