### ISSUE TITLE
State distribution printout is "1&2" for missing data

### ISSUE THREAD

**Issue by HeatherKates** [thej022214/corHMM#29]
Hello, I had previously opened an issue to ask about the correct way to code missing data in corHMM (issue #21). James advised me that using "?" was correct and this is what I have done:

tip,states
FMN_P115_WE01,Absent
FMN_P064_WC03,?
FMN_P113_WC05,Present

When corHMM runs, the printout reads:
Loading required package: ape
Loading required package: nloptr
Loading required package: GenSA
State distribution in data:
States: 1       1&2     2
Counts: 17006   396     7004

As you can see the "?" are printed as "1&2" in the state distribution message. I want to double check that this is just an issue with the text that is printed and that the "?" are NOT being interpreted by corHMM as polymorphic. They are missing.

Thank you!
Heather Rose

**Comment by jboyko** [comment]
Hi Heather,

Polymorphic data and missing data are actually handled in very similar ways within corHMM. In both cases the data is treated as unknown (although the biological interpretation is different). The only difference between polymorphic data and unknown data is that if you have more than two states you can specify which states are polymorphic, whereas with unknown data it's treated as all states are unknown. In your case of a binary character, there would be no difference in treating the data as polymorphic or unknown so the output is correct.

Best,
James

**Comment by HeatherKates** [comment]
Great, thanks James.
