### ISSUE TITLE
Using ancRECON with transition rates from corHMM

### ISSUE THREAD

**Issue by HeatherKates** [thej022214/corHMM#30]
Hello, in the manual the ancRECON section states that this stand alone function is to be used with rates estimated outside of corHMM. Is this only a practical consideration to clarify to the user that corHMM *can* do this or is there another reason to avoid using ancRECON with the output from corHMM? 

I'd like to perform replicate reconstructions using a fixed set of transition rates (I'm trying to determine to what extent variability in the reconstruction is due to different reconstructions vs. different transition rate estimates, and performing replicate runs of the corHMM function can't do that because the transition rate matrix is different each time), and my transition rates are estimated by corHMM.

Thanks!

**Comment by jboyko** [comment]
Hi Heather, you're correct that it's only a practical consideration - it's completely fine to use it for corHMM outputs or any rates. The one thing you need to be wary of when running the recon from a corHMM output is making sure the parameters are in the correct order. Here is some code I wrote that does that: `p = sapply(na.omit(c(corHMM_fit$index.mat)), function(x) na.omit(c(corHMM_fit$solution))[x])`. Double check that it works, but I think as long as you provide the index matrix and the parameter values it should be good. Sounds like a cool analysis, hope this helps!

Best,
James

**Comment by HeatherKates** [comment]
Thanks James! I'm not sure what the "correct order" of the parameters for ancRECON is - using the code you shared the parameters aren't in an order that makes sense to me...but I don't know that necessarily means it's not correct.
```
> corHMM_fit$solution
            (1,R1)       (2,R1)       (1,R2)       (2,R2)      (1,R3)
(1,R1)          NA 1.002498e-09 7.328407e-03           NA 0.031578469
(2,R1) 0.225449789           NA           NA 7.328407e-03          NA
(1,R2) 0.006892645           NA           NA 3.043414e-02 0.039738359
(2,R2)          NA 6.892645e-03 2.232514e-03           NA          NA
(1,R3) 0.000000001           NA 1.160631e-08           NA          NA
(2,R3)          NA 1.000000e-09           NA 1.160631e-08 0.000000001
> p = sapply(na.omit(c(corHMM_fit$index.mat)), function(x) na.omit(c(corHMM_fit$solution))[x])
> p
 [1] 2.254498e-01 1.000000e-09 7.328407e-03 6.892645e-03 1.000000e-09
 [6] 7.328407e-03 2.232514e-03 1.000000e-09 1.160631e-08 2.232514e-03
[11] 1.002498e-09 1.160631e-08 7.328407e-03 3.043414e-02 6.892645e-03
[16] 7.328407e-03 3.043414e-02
```

**Comment by jboyko** [comment]
Hi Heather,

The order is the same as a matrix is filled (by row). But, I'm glad you mentioned something because the quick code I wrote was actually wrong.
` p = sapply(1:max(corHMM_fit$index.mat, na.rm = TRUE), function(x) na.omit(c(corHMM_fit$solution))[na.omit(c(corHMM_fit$index.mat) == x)][1])`

That should be better. If you want to test it I'd suggest taking your result from fitting the corHMM model, then fitting the same dataset but this time using the code above to get p from your fitted model. Something like this:

`corHMM(phy = phy, data = data, rate.cat = 2, p = p, rate.mat = corHMM_fit$index.mat)`

This  should match exactly what your original model produced and the parameters should all be in the same place.

Best,
James

**Comment by HeatherKates** [comment]
Hi James, I don't think that R code to format p worked, but if I'm understanding the goal correctly I think I can fix that. However I'm guessing the vector p still isn't right even though it looks it to me- when run I get a meaningless/high AICc and low loglik. If I run with node estimation, I get an error. 

The solution matrix is:
```
> corHMM_fit$solution
            (1,R1)       (2,R1)       (1,R2)       (2,R2)      (1,R3)
(1,R1)          NA 1.002498e-09 7.328407e-03           NA 0.031578469
(2,R1) 0.225449789           NA           NA 7.328407e-03          NA
(1,R2) 0.006892645           NA           NA 3.043414e-02 0.039738359
(2,R2)          NA 6.892645e-03 2.232514e-03           NA          NA
(1,R3) 0.000000001           NA 1.160631e-08           NA          NA
(2,R3)          NA 1.000000e-09           NA 1.160631e-08 0.000000001
```
The vector is:
```
> p=as.vector(na.omit(as.vector(t(corHMM_fit$solution))))
> p
 [1] 1.002498e-09 7.328407e-03 3.157847e-02 2.254498e-01 7.328407e-03
 [6] 3.157847e-02 6.892645e-03 3.043414e-02 3.973836e-02 6.892645e-03
[11] 2.232514e-03 3.973836e-02 1.000000e-09 1.160631e-08 1.000000e-09
[16] 1.160631e-08 1.000000e-09
```
When run using a set of fixed parameters, p
```
> fixedparam=corHMM(phy=corHMM_fit$phy,data=corHMM_fit$data,rate.cat=3,p=p,rate.mat=corHMM_fit$index.mat,node.states="none")
You specified 'fixed.nodes=FALSE' but included a phy object with node labels. These node labels have been removed.
State distribution in data:
States: 1       1&2     2
Counts: 17002   396     7002
Calculating likelihood from a set of fixed parameters
> fixedparam$loglik
[1] -1e+06
> fixedparam$AICc
[1] 2000022
```
When node estimation is also attempted, error:
```
You specified 'fixed.nodes=FALSE' but included a phy object with node labels. These node labels have been removed.
State distribution in data:
States: 1       1&2     2
Counts: 17002   396     7002
Calculating likelihood from a set of fixed parameters
Finished. Inferring ancestral states using marginal reconstruction.
Error in liks.down[root, !col2rm] <- liks.down[root, !col2rm] * root.p :
  replacement has length zero
```

**Comment by jboyko** [comment]
One thing to note about your code `p=as.vector(na.omit(as.vector(t(corHMM_fit$solution))))`, is that it will get more parameters than are necessary for the model. What we want is the parameters to be in the same order as the index matrix and if to have the same total number of parameters as the maximum number within the index matrix. Also, I realize now that saying that they are inserted by column isn't always true in the case of HRM models. 

However it is odd, that the code I provided didn't work, when I run it on the dataset within corHMM it seems to work fine. Could you just double check for me that this method of getting p doesn't work?
`p = sapply(1:max(corHMM_fit$index.mat, na.rm = TRUE), function(x) na.omit(c(corHMM_fit$solution))[na.omit(c(corHMM_fit$index.mat) == x)][1])`

And here is an example from corHMM's default dataset:
```
data(primates)
phy <- multi2di(primates[[1]])
data <- primates[[2]]
corHMM_fit <- corHMM(phy = phy, data = data, rate.cat = 2, model = "SYM")
```
That gives us our model fit. Then if we want to examine fixed parameters:
```
p = sapply(1:max(corHMM_fit$index.mat, na.rm = TRUE), function(x) na.omit(c(corHMM_fit$solution))[na.omit(c(corHMM_fit$index.mat) == x)][1])
corHMM_fit_fixed <- corHMM(phy = phy, data = data, rate.cat = 2, model = "SYM", p = p)
```
And when I look at the results of `corHMM_fit` and `corHMM_fit_fixed` they are identical and all the parameters are in the right place. 

corHMM_fit:
```
Fit
      -lnL      AIC     AICc Rate.cat ntax
 -41.54992 95.09984 96.68475        2   60

Legend
    1     2     3 
"0_0" "0_1" "1_1" 

Rates
           (1,R1)     (2,R1)     (3,R1)      (1,R2)      (2,R2)     (3,R2)
(1,R1)         NA 8.99706896         NA 0.039065810          NA         NA
(2,R1) 8.99706896         NA 0.03031649          NA 0.039065810         NA
(3,R1)         NA 0.03031649         NA          NA          NA 0.03906581
(1,R2) 0.01742337         NA         NA          NA 0.000000001         NA
(2,R2)         NA 0.01742337         NA 0.000000001          NA 0.01181521
(3,R2)         NA         NA 0.01742337          NA 0.011815214         NA

Arrived at a reliable solution 
```

corHMM_fit_fixed:
```
Fit
      -lnL      AIC     AICc Rate.cat ntax
 -41.54992 95.09984 96.68475        2   60

Legend
    1     2     3 
"0_0" "0_1" "1_1" 

Rates
           (1,R1)     (2,R1)     (3,R1)      (1,R2)      (2,R2)     (3,R2)
(1,R1)         NA 8.99706896         NA 0.039065810          NA         NA
(2,R1) 8.99706896         NA 0.03031649          NA 0.039065810         NA
(3,R1)         NA 0.03031649         NA          NA          NA 0.03906581
(1,R2) 0.01742337         NA         NA          NA 0.000000001         NA
(2,R2)         NA 0.01742337         NA 0.000000001          NA 0.01181521
(3,R2)         NA         NA 0.01742337          NA 0.011815214         NA

Arrived at a reliable solution 
```

**Comment by HeatherKates** [comment]
Hi James, oops - I'm sorry. The issue was/is that I still don't understand what the vector of fixed parameters is supposed to look like. I meant that your code "did not work" in that the rates were in the wrong order *if* the right order is row by row, because you originally wrote 
> The order is the same as a matrix is filled (by row)
However - it totally works in when corHMM is actually run as you described. I didn't even get to checking that because I just viewed the vector that it produced and it did not look as I expected. 

I will just save your code for doing this as I think it's OK if I don't understand how the ordering of parameters works for now.

Thank you - and sorry for the wasted time after you shared the working code!

**Comment by jboyko** [comment]
Oh not wasted time at all! I'm sorry, when you said it didn't work I thought it may be because of a different matrix structure in your data and wanted to make sure that it worked on the default dataset I'd been testing it on. 

I can appreciate wanting to know how the code works so let me try explain exactly what the code does in words. So the sapply function is based on your index matrix (which tells corHMM where each of your parameters goes). It is a function of x and will move from 1 to the maximum number of free parameters (e.g., in an "ER" there is only one free parameter). So this code will start at 1 in your index matrix, find where all the 1s are in the index matrix (`na.omit(c(corHMM_fit$index.mat) == x)`) then it will match the location of the 1s to the solution matrix which contains the actual parameter values (`na.omit(c(corHMM_fit$solution))[na.omit(c(corHMM_fit$index.mat) == x)]`). Then, because we don't need multiple copies of the same parameter we just take the first value that comes up `na.omit(c(corHMM_fit$solution))[na.omit(c(corHMM_fit$index.mat) == x)][1]`. We then repeat this process for all the x independent parameters within the index matrix (`sapply(1:max(corHMM_fit$index.mat, na.rm = TRUE, ...)`).

Hopefully that makes more sense. 

Best,
James

**Comment by HeatherKates** [comment]
Ah - Thank you. I knew there was probably a reason there was more to it than just making it a vector and removing the NA's but figured I'd try something!

While we're here and this has all been sorted out by testing p=p in corHMM()...is there actually any reason to use ancRECON? I just ran corHMM() with p=p and node.states="marginal" and it ran fine and gave me the estimated states.

**Comment by jboyko** [comment]
Hmm, come to think about it, I guess not actually. The results should be identical.

**Comment by HeatherKates** [comment]
Thanks James!
