### ISSUE TITLE
length of 'dimnames' [1] not equal to array extent

### ISSUE THREAD

**Issue by Victaphanta** [thej022214/corHMM#33]
Hi James,

I and reconstructing ancestral for 35 characters that can be polymorphic per tip taxa.  Most run just fine and give results.  Some fail to run with the following error given:

"Loading required package: nloptr
Loading required package: GenSA
Loading required package: tidyr
State distribution in data:
States:	0&1	0&1&2	0&1&2&3	1&2	1&2&3	1&2&3&4	2	2&3	2&3&4	2&3&4&5	3	3&4	?	
Counts:	1	1	1	4	8	7	3	9	13	3	2	8	0	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent
Calls: sourceWithProgress ... rate.cat.set.corHMM.JDB -> getStateMat4Dat -> rownames<-
Execution halted"

This is the syntax I am using which works fine on the other characters.

"recon04a <- rayDISC(MyTree,MyMorph,model="SYM",charnum=4,node.states="marginal",root.p=c(1,0,0,0,0,0),lewis.asc.bias=TRUE)"

Not sure where to start to resolve this issue as no initial output is given.  I know this is a hideous polymorphic dataset, it is a subset of a larger dataset with states collated at the family level.

I can send you the data if this would help.

Thanks

Adnan

**Comment by jboyko** [comment]
Hi Adnan, 

If you could send the dataset to me at jboyko@uark [dot] edu I can take a look.

Best,
James

**Comment by jboyko** [comment]
This bug has been resolved.
