### ISSUE TITLE
Suggestion: function "makeSimmap" return class "multiSimmap"

### ISSUE THREAD

**Issue by Caetanods** [thej022214/corHMM#39]
Function "makeSimmap" return object of class "list". Adding "multiSimmap" to the class can make interaction with "phytools" simpler.

Solution:

```
class_to_append <- ifelse(test = nSim > 1, yes = "multiSimmap", no = "simmap")
class(obj) <- append(class(obj), class_to_append)
return(obj)
```

**Comment by jboyko** [comment]
Dearest Dr. Caetano,
*ahem* 
https://github.com/thej022214/corHMM/blob/6cfa4c94e48f93c310e49e7127c67aa3f0348927/R/makeSimmap.R#L47

Actually though, I think the newest version does this. Unless I misunderstand what you're asking.

**Comment by Caetanods** [comment]
Awesome! I am using the RCran version.
