### ISSUE TITLE
Missing states 

### ISSUE THREAD

**Issue by thej022214** [thej022214/corHMM#4]
Turns out different functions have different requirements for how to score missing characters. In corHMM "NA" is considered missing, whereas in rayDISC "?" assumes it is missing. 

This needs to be standardized.

**Comment by jcoliver** [comment]
@thej022214 Yes, standardization needs to happen. You want me on this?

**Comment by jcoliver** [comment]
I think the approach used in corHMM is the most appropriate, by the way (NA = missing).

**Comment by thej022214** [comment]
JEFF!!! I am not sure what corDISC uses, but I can deal with that one. But if you wanted to take a crack at rayDISC that would be sweet. Note, that I've made some new changes to rayDISC, though it should not impact what you are doing.

**Comment by thej022214** [comment]
I just fixed corHMM. All seems to work fine. Had to deal with issues with phangorn and generating starting values, but other than, seems good.

**Comment by jcoliver** [comment]
Updated rayDISC with similar fix as corHMM, while still supporting "?" as missing state (if user has ?, it gets replaced by NA before analysis). Also made some updates to conform to variable names in corHMM.

**Comment by thej022214** [comment]
Cool! I will check it out. I am sure you noticed, but I had an issue with phangorn and starting values when there was an NA. I don't remember what rayDISC does for a starting value, but I will take a look.

**Comment by thej022214** [comment]
Should be fixed.
