### ISSUE TITLE
Showing tip states for PlotRECON?

### ISSUE THREAD

**Issue by ymilesz** [thej022214/corHMM#43]
Hi,

  I am using corHMM's raydisc function to do ancestral state reconstruction of discrete traits, however I cannot figure out how to show each tip state, as the pie charts are only displayed at the nodes. I tried looking at PlotRECON and RayDISC's documents but cannot find it. It seems like it would be easy to do but I can't figure it out.

Thanks,

Miles

**Comment by jcoliver** [comment]
You should be able to pass `show.tip.label = TRUE` to `plotRECON()` to show tip states.

Note you might also consider using `corHMM()` in place of `rayDISC()`. All the functionality of the latter function is now in `corHMM()` (set `rate.cat = 1`).

**Comment by ymilesz** [comment]
Hi Jeff,

  Thank you for the quick response, I've tried corHMM and it looks good, although the show.tip.label = TRUE only added the tip labels, not the original states. 
  
  plotRECON(phy, phy_corHMM_ER$states, 
          piecolors=cols, cex=0.5, pie.cex=0.4, file=NULL,height=50, width=10, 
          show.tip.label=TRUE, label.offset=0.001, no.margin=TRUE)

**Comment by jcoliver** [comment]
Ah, yes, I should have looked closer. Perhaps try using `ape::tiplabels()` after calling `plotRECON()`? Section 1.1 in the package vignette shows an example of `tiplabels()` https://github.com/thej022214/corHMM/blob/master/vignettes/corHMMv2.1-vignette.pdf

**Comment by ymilesz** [comment]
Got it, thank you!
