### ISSUE TITLE
what is rate.mat.index

### ISSUE THREAD

**Issue by emoore51** [thej022214/corHMM#6]
In the help for rate.mat.maker, it says to "Use rate.mat.index to see what correspond to which transition." It's not clear how to actually use this: rate.mat.index isn't an exposed function nor an element of the rate matrix.

@bomeara told me to write this.

**Comment by jcoliver** [comment]
Thanks, @emoore51 . Updated manual to better convey the utility of `rate.mat.maker` and resultant `rate.mat.index`.
