### ISSUE TITLE
Understanding columns in tip.states from corhmm output

### ISSUE THREAD

**Issue by alrichardbollans** [thej022214/corHMM#62]
I am running corHMM and outputting tip states (`get.tip.states = TRUE`). From the output $tip.states, what I really would like is for each variable to know which columns indicate a '0' and which columns indicate a '1'.

In the simple case that only one binary variable is input and rate.cat=1, the output is two columns with the first being probability of state 0 and the second being probability of state 1. However, including more variables and higher rate.cats leaves columns that are more difficult to interpret and I'm not sure how to go about this for a generic value of rate.cat and any number of additional variables.

**Comment by jboyko** [comment]
The names should be the same as the ancestral state reconstruction output (node states). However, I've just pushed a change that will name the columns explicitly by the input trait and rate class. If you install the github version it should resolve the issue. Hope that helps!

**Comment by alrichardbollans** [comment]
Amazing, thanks!
