### ISSUE TITLE
rayDISC assumes first column is taxon names

### ISSUE THREAD

**Issue by jcoliver** [thej022214/corHMM#8]
This needs to be made clearer in documentation or a workaround / check should be implemented. Right now it results in a "Character X is invariant" message if the first column is not taxon names.

**Comment by thej022214** [comment]
Ah. Good call. I'll take a close look at this soon and clarify things in the manual.

**Comment by jcoliver** [comment]
@thej022214 Heh, I assigned this to myself, but if you get to it before me, go for it.
